# Generated by Django 4.2.3 on 2023-07-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',

        ), migrations.RemoveField(
            model_name='user',
            name='is_active',

        ), migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
